name: echochamber
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_ui_auth: ^1.12.1
  
  # State Management
  provider: ^6.1.1
  
  # Routing
  go_router: ^13.0.1
  
  # UI Components
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.2
  path: ^1.8.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0

flutter:
  uses-material-design: true 