name: echochamber
description: A music-focused video-sharing platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  
  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  firebase_admin: ^0.3.0+1
  firebase_analytics: ^11.4.2
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # Video Processing
  ffmpeg_kit_flutter: ^6.0.3
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.2
  path: ^1.8.3
  logger: ^2.0.2+1
  go_router: ^14.0.0
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0

flutter:
  uses-material-design: true 