// Mocks generated by Mockito 5.4.5 from annotations
// in echochamber/test/widgets/email_sign_up_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:echochamber/models/user_model.dart' as _i4;
import 'package:echochamber/repositories/user_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> createUser(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(String? userId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [userId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastActive(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastActive, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> followUser(String? userId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [userId, targetUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unfollowUser(String? userId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [userId, targetUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> getUserFollowers(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFollowers, [userId]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> getUserFollowing(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFollowing, [userId]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Future<void> updateOnboardingProgress(
    String? userId,
    String? step,
    bool? completed,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnboardingProgress, [
              userId,
              step,
              completed,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserStats(String? userId, Map<String, int>? stats) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStats, [userId, stats]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addRecentVideo(
    String? userId,
    Map<String, dynamic>? videoData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentVideo, [userId, videoData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
