// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIbnnKIzXvHkqZpltL_ScohK5LgMuhmPA',
    appId: '1:517900340346:web:4efb12300fbe542ccc3fc3',
    messagingSenderId: '517900340346',
    projectId: 'echo-chamber-8fb5f',
    authDomain: 'echo-chamber-8fb5f.firebaseapp.com',
    storageBucket: 'echo-chamber-8fb5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwUBzW9ips_JorojFjTDm5prHrs3pWjIY',
    appId: '1:517900340346:android:33327e9325122d49cc3fc3',
    messagingSenderId: '517900340346',
    projectId: 'echo-chamber-8fb5f',
    storageBucket: 'echo-chamber-8fb5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMqpId5vgcVwYV5qY5UaSPJLKliidTPw',
    appId: '1:517900340346:ios:83f47d6b74eef04ecc3fc3',
    messagingSenderId: '517900340346',
    projectId: 'echo-chamber-8fb5f',
    storageBucket: 'echo-chamber-8fb5f.firebasestorage.app',
    iosBundleId: 'com.example.echochamber',
  );

}